workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.hybridassistant"

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
